---
- name: NMAP hosts and report
  hosts: localhost
  remote_user: anton
  become: true
  become_method: sudo

  tasks:
  - name: install nmap
    apt:
      name: nmap
      state: present

  - name: copy nmap targets list
    copy:
      src: ./targets.txt
      dest: ~/targets.txt
      mode: '0644'

  - name: run nmap
    shell: "nmap -iL ~/targets.txt -p 80 -oG -"
    register: nmap_result

  - name: Nmap output
    debug:
      msg: "{{nmap_result.stdout_lines }}"

